### ISSUE TITLE
there is some erros

### ISSUE THREAD

**Issue by boboee** [hhyo/mybatis-mapper2sql#3]
line 156  in convert.py 
prefeix shoud not be Null

change :

         if prefix:
            convert_string = prefix + ' ' + convert_string

**Comment by hhyo** [comment]
这个和 #2 修改后提交一个PR吧，顺带补充下相关xml测试

**Comment by boboee** [comment]
是没有权限吗，还是怎么滴，老是失败，不知道怎么弄PR，老哥，还是您自己改改吧。我的问题已经描述好了。
when child.tag = where ,prefix_overrides shoud be '(and|or)' not 'and|or'

example:

yn = 1 and (type = 40 or type= 60)
if prefix_overrides is 'and|or' ,
it will be this: yn = 1 and (type = 40 type= 60)

正则表达式这一个，如果不加括号，那么where 语句中的  type = 40 or type= 60   中间的or会被删掉



还有一个问题：
      convert.py里面的滴153行

    
![image](https://user-images.githubusercontent.com/13548903/55313573-ad422200-549a-11e9-9269-a86e451c08ed.png)



为什么要这么多，如果suffix_overrides不为空，那么，这个地方会包找不到group1，不知道是不是你们的特殊需求。

**Comment by hhyo** [comment]
group1应该是为了提取注释，可以不用，已修改，pip可以直接更新0.1.5版本，感谢反馈
