### ISSUE TITLE
convert where issues 

### ISSUE THREAD

**Issue by boboee** [hhyo/mybatis-mapper2sql#4]
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd" >
<mapper namespace="xxx.xxx.xxxDao">

    <sql id="Join_Where_List">
        <where>
            yn = 1
            and (inspection_type = 40 or inspection_type = 60)
        </where>
    </sql>

    <select id="find" resultType="java.lang.Integer" >
        SELECT
        count(*)
        from inspection
        <include refid="Join_Where_List"/>
    </select>

</mapper>

这个测试mapper
![image](https://user-images.githubusercontent.com/13548903/55317684-97852a80-54a3-11e9-8406-731454c2f97b.png)

生成的sql：
        SELECT
        count(*)
        from inspection
        yn = 1
        and (inspection_type = 40  inspection_type = 60)

您的意思应该是：如果最前面有and 或者or 就删掉

但是如果:prefix_overrides='and|or'
生成的sql里面：   后面的 or 就会被删掉

改为：prefix_overrides='(and|or)'  就好了

欢迎校验。对正则不是很了解，可能无解大神的意思。

**Comment by hhyo** [comment]
是删除最前面的(and|or)，否则会出现 where and 这种情况，本来改好了，在改python 3.4支持又少了（），我再更新一版吧，test case现在没有做断言，后续我补上

**Comment by hhyo** [comment]
0.1.7版本麻烦验证一下
