### ISSUE TITLE
suffixOverrides正则匹配不正确

### ISSUE THREAD

**Issue by chrobin** [hhyo/mybatis-mapper2sql#5]
https://github.com/hhyo/mybatis-mapper2sql/blob/14b070356f71d9501c73040f2e81760836d09f50/mybatis_mapper2sql/convert.py#L152

convert.py第152行的正则表达式不正确，原意应该是想匹配到最后一个$suffixOverrides和--注释，但实际上并不能匹配到，例如以下的这种xml：
```xml
<select id="xxx>
    select * from tbl
    <trim prefix="where" suffixOverrides="AND|OR">
        <if test="a!=null">
            a=#{a} AND
        </if>
        <if test="b!=null">
            b=#{b} AND
        </if>
        <if test="b!=null">
            c=#{c}
        </if>
    </trim>
</select>
```
在python3.5下会被解析成
```sql
select * from tbl where a=? b=? and c=?
```
该sql不正确，正则应该是匹配并替换了a=?后面的and，而不是最后一个and
在python3.4下会报错

**Comment by hhyo** [comment]
升级0.1.7测试下
这是在0.1.7下面的测试结果
![image](https://user-images.githubusercontent.com/8842982/56111593-1e99ce80-5f8b-11e9-8299-08959ae83702.png)

**Comment by chrobin** [comment]
多谢，0.1.7已解决该问题
