### ISSUE TITLE
Asking for help to solve the dependency conflict issues of the mybatis-mapper2sql's downstream projects

### ISSUE THREAD

**Issue by NeolithEra** [hhyo/mybatis-mapper2sql#8]
Hi, your downstream project **_Archery_** suffered from a dependency conflict issue caused by **mybatis-mapper2sql 0.1.8**.

As shown in the following links:
https://github.com/hhyo/Archery/issues/356.

Could you please loose the version ranges of your direct dependency **sqlparse == 0.2.4** to **sqlparse >= 0.2.4**, to remove this dependency hell of downstream projects?

Thanks for your help!

Neolith

**Comment by hhyo** [comment]
Thanks for the feedback. I'll take care of it.
